In [ ]:
import numpy as np

# From a list
my_list = [1, 2, 3, 4, 5]
array_from_list = np.array(my_list)
print(f"---- 1D Array ---- \n{array_from_list}")
# From a nested list (creates a 2D array)
nested_list = [[1, 2, 3], [4, 5, 6]]
two_d_array = np.array(nested_list)
print(f"---- 2D Array ---- \n {two_d_array}")


---- 1D Array ---- 
[1 2 3 4 5]

---- 2D Array ---- 
 [[1 2 3]
 [4 5 6]]


In [28]:
# Concatenate
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concatenated_arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenated:\n", concatenated_arr)

Concatenated:
 [[1 2]
 [3 4]
 [5 6]]


In [11]:
# 1D Array Example
import numpy as np

# Create 1D array
arr1 = np.array([10,20,30,40,50])
print("Original 1D Array:",arr1)
print("Shape:", arr1.shape) # Shape:  dimensions of the array

Original 1D Array: [10 20 30 40 50]
Shape: (5,)


In [12]:
# Basic Operations
print("Data Type:", arr1.dtype)
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Maximum:", arr1.max())
print("Minimum:", arr1.min())

Data Type: int64
Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [13]:
# Element-wise operations

print("Array + 5:", arr1 + 5)
print("Array * 2:", arr1 * 2)

Array + 5: [15 25 35 45 55]
Array * 2: [ 20  40  60  80 100]


In [14]:
# Slicing
print("First 3 elements:", arr1[:3])
print("Last 2 elements:", arr1[-2:])

First 3 elements: [10 20 30]
Last 2 elements: [40 50]


In [15]:
# 2D Array Example
import numpy as np

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Original 2D Array:\n", arr2)
print("Shape:", arr2.shape) # Shape: (2, 3) - 2 rows, 3 columns

Original 2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [17]:
# Accessing Elements 
print("Element at (0, 1):", arr2[0, 1]) # Element at first row, second column
# Rows and Columns
print("First row:", arr2[0]) # First row
print("Second column:", arr2[:, 1]) # Second column

Element at (0, 1): 2
First row: [1 2 3]
Second column: [2 5]


In [18]:
# Transpose
print("Transposed Array:\n", arr2.T) # Transpose: rows become columns and vice versa

Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [19]:
# Mathematical operations
print("Row-wise sum:", np.sum(arr2, axis=1)) # Row-wise sum
print("Column-wise sum:", np.sum(arr2, axis=0)) # Column-wise sum

Row-wise sum: [ 6 15]
Column-wise sum: [5 7 9]


In [ ]:
# Reshaping

reshaped = arr2.reshape((3, 2))
print("Reshaped Array:\n", reshaped) # Reshape to 3 rows, 2 columns

# Flattening 
flat = arr2.flatten()
print("Flattened Array:", flat) # Flatten to 1D array

Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]
Flattened Array: [1 2 3 4 5 6]


In [22]:
first_row = np.array([arr2[0]]) # First row as a new 2D array
print("First row as new array:\n", first_row) # First row as new 2D array
print("Row-wise sum:", np.sum(first_row, axis=1)) # Row-wise sum of the new array

First row as new array:
 [[1 2 3]]
Row-wise sum: [6]


In [26]:
# Create a 2D array of marks for 3 students in 4 subjects marks.

marks = np.array([[85, 90, 78, 92], [88, 76, 95, 89], [90, 85, 80, 88]])
print("Marks Array:\n", marks)
print()
# 2. Calculate average marks for each student (row-wise).
first_row = np.array([marks[0]])
print("First row:\n", first_row)
average_marks = np.mean(first_row, axis=1)
print("Average Marks Of student 1:", average_marks)
print()

second_row = np.array([marks[1]])
print("Secong row:\n", first_row)
average_marks = np.mean(second_row, axis=1)
print("Average Marks Of student 2:", average_marks)
print()

third_row = np.array([marks[2]])
print("Third row:\n", first_row)
average_marks = np.mean(third_row, axis=1)
print("Average Marks Of student 3", average_marks)
print()

Marks Array:
 [[85 90 78 92]
 [88 76 95 89]
 [90 85 80 88]]

First row:
 [[85 90 78 92]]
Average Marks Of student 1: [86.25]

Secong row:
 [[85 90 78 92]]
Average Marks Of student 2: [87.]

Third row:
 [[85 90 78 92]]
Average Marks Of student 3 [85.75]



In [27]:
# Create two arrays and perform element-wise addition, subtraction, multiplication.
arr3 = np.array([1, 2, 3])
arr4 = np.array([4, 5, 6])

print("Array 1:", arr3)
print("Array 2:", arr4)

print("Element-wise Addition:", arr3 + arr4)
print("Element-wise Subtraction:", arr3 - arr4)
print("Element-wise Multiplication:", arr3 * arr4)

Array 1: [1 2 3]
Array 2: [4 5 6]
Element-wise Addition: [5 7 9]
Element-wise Subtraction: [-3 -3 -3]
Element-wise Multiplication: [ 4 10 18]
